In [45]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import seaborn as sns 
import matplotlib.pyplot as plt

In [46]:
df = pd.read_csv("Groceries_dataset.csv")
df.head(3)

   Member_number        Date itemDescription
0           1808  21-07-2015  tropical fruit
1           2552  05-01-2015      whole milk
2           2300  19-09-2015       pip fruit

In [47]:
# Extract unique items from the 'itemDescription' column

unique_items = df['itemDescription'].unique()

# Count the number of unique items

num_unique_items = len(unique_items)

# Print the result

print(f'Number of unique products: {num_unique_items}')

Number of unique products: 167

In [48]:
# Count the occurrences of each product

product_counts = df['itemDescription'].value_counts()

# Display the results

print("Product names and their counts:")

print(product_counts)

Product names and their counts:
itemDescription
whole milk               2502
other vegetables         1898
rolls/buns               1716
soda                     1514
yogurt                   1334
                         ...
rubbing alcohol             5
bags                        4
baby cosmetics              3
kitchen utensil             1
preservation products       1
Name: count, Length: 167, dtype: int64

In [49]:
# Convert the data into the required format for the Apriori algorithm.

# We need to create a list of transactions where each transaction is a list of items.



transactions = df.groupby('Member_number')['itemDescription'].apply(list).values.tolist()

# Display the first few transactions

# print(transactions[:5])

In [50]:
te = TransactionEncoder()

# Transform the transaction data into a binary matrix

te_ary = te.fit(transactions).transform(transactions)

In [51]:
# Convert the binary matrix into a DataFrame.

df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

df_encoded.head(3)

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,True,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [74]:
# Apply the Apriori algorithm

frequent_itemsets = apriori(df_encoded, min_support=0.07, use_colnames=True).sort_values(by = ["support"])

# Display the frequent itemsets

print(frequent_itemsets)


# support value of 0.050026 means that the itemset appears in approximately 5.00% of the transactions in your dataset.
# support value of 0.050026 means that the itemset is found in about 5 out of every 100 transactions.

     support                                itemsets
47  0.070292             (domestic eggs, whole milk)
69  0.071575               (root vegetables, yogurt)
49  0.071575              (other vegetables, pastry)
82  0.071832  (other vegetables, whole milk, yogurt)
45  0.071832              (rolls/buns, citrus fruit)
..       ...                                     ...
37  0.282966                                (yogurt)
32  0.313494                                  (soda)
28  0.349666                            (rolls/buns)
24  0.376603                      (other vegetables)
36  0.458184                            (whole milk)

[83 rows x 2 columns]

In [53]:
# Generate association rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

# Display the association rules

print(rules)

                                            antecedents         consequents  \
0                                            (UHT-milk)        (whole milk)
1                                                (beef)        (whole milk)
2                                        (bottled beer)        (whole milk)
3                                       (bottled water)        (whole milk)
4                                         (brown bread)        (whole milk)
...                                                 ...                 ...
1112  (rolls/buns, other vegetables, shopping bags, ...        (whole milk)
1113    (rolls/buns, whole milk, shopping bags, yogurt)  (other vegetables)
1114  (other vegetables, whole milk, shopping bags, ...        (rolls/buns)
1115       (rolls/buns, other vegetables, soda, yogurt)        (whole milk)
1116             (rolls/buns, whole milk, soda, yogurt)  (other vegetables)

      antecedent support  consequent support   support  confidence      lift  \
0               0.078502            0.458184  0.040534    0.516340  1.126928
1               0.119548            0.458184  0.064135    0.536481  1.170886
2               0.158799            0.458184  0.085428    0.537964  1.174124
3               0.213699            0.458184  0.112365    0.525810  1.147597
4               0.135967            0.458184  0.069779    0.513208  1.120091
...                  ...                 ...       ...         ...       ...
1112            0.014110            0.458184  0.010005    0.709091  1.547613
1113            0.016932            0.376603  0.010005    0.590909  1.569049
1114            0.017958            0.349666  0.010005    0.557143  1.593355
1115            0.020010            0.458184  0.013597    0.679487  1.483002
1116            0.024628            0.376603  0.013597    0.552083  1.465954

      leverage  conviction  zhangs_metric
0     0.004565    1.120242       0.122227
1     0.009360    1.168919       0.165762
2     0.012669    1.172672       0.176297
3     0.014452    1.142615       0.163569
4     0.007481    1.113034       0.124087
...        ...         ...            ...
1112  0.003540    1.862494       0.358908
1113  0.003629    1.523858       0.368918
1114  0.003726    1.468495       0.379203
1115  0.004428    1.690467       0.332342
1116  0.004322    1.391769       0.325876

[1117 rows x 10 columns]